### ISSUE TITLE
Implement storageClass assignment for PVs in target cluster

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#259]
After the PVs have been discovered and the user has designated them either "copy" or "move", the user will need the ability to choose a storage class that will be used in the target cluster for the PV. This would support use cases of migrating NFS backed PVs to something like EBS storage.

The PV discovery process should take care of adding the source PV's storageclass to the discovered PV section, if it exists. (Not present in the controller yet, issue filed: https://github.com/fusor/mig-controller/issues/134). To get the available storageclasses the user can choose from on the target cluster, the UI needs to query that cluster with `LIST storageclasses`.

Here's an example storage class from a target OCP4 cluster, for EBS:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: null
  name: gp2
  ownerReferences:
  - apiVersion: v1
    kind: clusteroperator
    name: storage
    uid: d4bc5ea4-782f-11e9-a701-0a4e52dea9a2
parameters:
  encrypted: "true"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

We also think it would be useful to include the `provisioner` field in the dropdown string, because it adds more information than just a name like `gp2`. Ex dropdown string: `gp2:kubernetes.io/aws-ebs`.

Note: PVs that have been designated "move" should be left out of this list, because the storageclass assignment is not applicable.

FYI @vconzola
