### ISSUE TITLE
When a migplan is created and in a not ready state, upper right card thinks its complete

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-ui#346]
![image](https://user-images.githubusercontent.com/410933/61386221-e2278880-a881-11e9-860b-4fb1d869d082.png)

I created a migplan referring to a source cluster, then I deleted that source cluster. That will throw the plan into a "Not Ready" state with the following critical condition:

```
    conditions:
    - category: Critical
      lastTransitionTime: 2019-07-17T14:50:54Z
      message: The `srcMigClusterRef` must reference a `migcluster`.
      reason: NotFound
      status: "True"
      type: InvalidSourceClusterRef
```

This causes the UI to display an incorrect state in the upper right part of the card as seen in the screenshot.
