### ISSUE TITLE
Improve Plan status logic

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/mig-ui#371]
During testing the ns on the source cluster was accidentally removed. The migration picked up the change, but the UI displayed only that the plan is `Not Ready`. It was hard to notice the migration failed, even knowing it's background.
Here is how it is displayed now:
![image](https://user-images.githubusercontent.com/32226600/61884627-dfb9d400-aefc-11e9-9b19-f1a7aa02165d.png)

Migmigration status:
```
status:
  conditions:
  - category: Critical
    lastTransitionTime: 2019-07-25T14:36:50Z
    message: The referenced `migPlanRef` does not have a `Ready` condition.
    status: "True"
    type: PlanNotReady
  phase: StageRestoreCreated
  startTimestamp: 2019-07-25T14:35:27Z
```

Migplan status:
```
status:
  conditions:
  - category: Critical
    lastTransitionTime: 2019-07-25T14:36:50Z
    message: Namespaces [mysql-persistent] not found on the source cluster.
    reason: NotFound
    status: "True"
    type: NamespaceNotFoundOnSourceCluster
```

Migplan correctly recognized the issue, and it should be displayed in the UI too. Should be related to https://github.com/fusor/mig-ui/issues/291 https://github.com/fusor/mig-ui/issues/355 and https://github.com/fusor/mig-ui/issues/331
